/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author prodr
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);//x se cierra
        setName("CORONAPP");
        setTitle("Coronapp");
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }
    public Image getIcImage(){
        Image icono_app = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/icon.png"));
        return icono_app;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        iconUsuario = new javax.swing.JLabel();
        ingresaUsuario = new javax.swing.JTextField();
        iconPassword = new javax.swing.JLabel();
        ingresaPassword = new javax.swing.JPasswordField();
        buttomSalir = new javax.swing.JButton();
        buttomIngresar = new javax.swing.JButton();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/WhatsApp Image 2020-03-18 at 21.00.12.jpeg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        titulo.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("CORONAAPP");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/WhatsApp Image 2020-03-18 at 21.00.22 (2).jpeg"))); // NOI18N
        getContentPane().add(iconUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 133, -1, -1));

        ingresaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        ingresaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        ingresaUsuario.setText("jTextField1");
        getContentPane().add(ingresaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 133, 207, 32));

        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/WhatsApp Image 2020-03-18 at 21.00.17 (1).jpeg"))); // NOI18N
        getContentPane().add(iconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 180, -1, -1));

        ingresaPassword.setBackground(new java.awt.Color(255, 255, 255));
        ingresaPassword.setText("jPasswordField1");
        getContentPane().add(ingresaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 180, 207, 32));

        buttomSalir.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttomSalir.setText("SALIR");
        buttomSalir.setToolTipText("Para SALIR");
        buttomSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomSalirActionPerformed(evt);
            }
        });
        getContentPane().add(buttomSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        buttomIngresar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        buttomIngresar.setText("INGRESAR");
        buttomIngresar.setToolTipText("Haga click para ingresar");
        buttomIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(buttomIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/WhatsApp Image 2020-03-18 at 21.00.17.jpeg"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttomSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttomSalirActionPerformed

    private void buttomIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttomIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttomIngresar;
    private javax.swing.JButton buttomSalir;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconUsuario;
    private javax.swing.JPasswordField ingresaPassword;
    private javax.swing.JTextField ingresaUsuario;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
