/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial;

import Controlador.datos;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author duily
 */
public class vista extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    Object dato [] = new Object [5];
    int fila = 0;
    
    
    /**
     * Creates new form vista
     */
    public vista() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
        modelo.addColumn("Mascota");
        modelo.addColumn("Raza");
        modelo.addColumn("Edad");
        modelo.addColumn("Nombre Dueño");
        modelo.addColumn("Celular");
        
        
        jTable1.setModel(modelo);
    
    

    }
    public void anadir(String mascota,String Raza,int edad,String Nombre_dueno,int telefono){
        dato[0]=mascota;
        dato[1]=Raza;
        dato[2]=edad;
        dato[3]=Nombre_dueno;
        dato[4]=telefono;
        
        modelo.addRow(dato);
        
    }
    public void eliminar(int fila){
        modelo.removeRow(fila);
    }
    
    public void modificar(int fila,String mascota,String Raza,int edad,String Nombre_dueno,int telefono){
        modelo.removeRow(fila);
        dato[0]=mascota;
        dato[1]=Raza;
        dato[2]=edad;
        dato[3]=Nombre_dueno;
        dato[4]=telefono;
        modelo.addRow(dato);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_telefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_mascota = new javax.swing.JTextField();
        txt_raza = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_nombredueno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 14, 370, 350));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 260, -1));

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        txt_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mascotaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 260, -1));
        getContentPane().add(txt_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 260, -1));
        getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 260, -1));
        getContentPane().add(txt_nombredueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 260, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 70, -1));

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jLabel1.setText("Telefono(ingrese un telefono):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 20));

        jLabel2.setText("Nombre de la mascota:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel3.setText("Raza:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 20));

        jLabel4.setText("Edad (ingrese un numero entero):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 20));

        jLabel5.setText("Nombre de Dueño:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String mascota = txt_mascota.getText();
            String raza = txt_raza.getText();
            int edad =Integer.parseInt(txt_edad.getText());
            String nombre_dueno = txt_nombredueno.getText();
            int telefono = Integer.parseInt(txt_telefono.getText());
            if(txt_mascota.getText().equals("") || txt_raza.getText().equals("") || txt_edad.getText().equals("") || txt_nombredueno.getText().equals("") || txt_telefono.getText().equals("")){
                JOptionPane.showMessageDialog(null, "llene todos los campos");    
            }
            else{
                txt_mascota.setText(null);
                txt_raza.setText(null);
                txt_edad.setText(null);
                txt_nombredueno.setText(null);
                txt_telefono.setText(null);
                anadir(mascota, raza, edad, nombre_dueno, telefono);           
            }
        
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"valide que ingreso un numero entero en la edad y telefono");
        }

        
        
               
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mascotaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        eliminar(fila);
        txt_mascota.setText(null);
        txt_raza.setText(null);
        txt_edad.setText(null);
        txt_nombredueno.setText(null);
        txt_telefono.setText(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.rowAtPoint(evt.getPoint());
        txt_mascota.setText(String.valueOf(jTable1.getValueAt(fila, 0)));
        txt_raza.setText(String.valueOf(jTable1.getValueAt(fila, 1)));
        txt_edad.setText(String.valueOf(jTable1.getValueAt(fila, 2)));
        txt_nombredueno.setText(String.valueOf(jTable1.getValueAt(fila, 3)));
        txt_telefono.setText(String.valueOf(jTable1.getValueAt(fila, 4)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        try{    
            String mascota = txt_mascota.getText();
            String raza = txt_raza.getText();
            int edad =Integer.parseInt(txt_edad.getText());
            String nombre_dueno = txt_nombredueno.getText();
            int telefono = Integer.parseInt(txt_telefono.getText());
            if(txt_mascota.getText().equals("") || txt_raza.getText().equals("") || txt_edad.getText().equals("") || txt_nombredueno.getText().equals("") || txt_telefono.getText().equals("")){
                JOptionPane.showMessageDialog(null, "valide de haber seleccionado un registro a modificar");
            }
            else{
                modificar(fila, mascota, raza, edad, nombre_dueno, telefono);
                txt_mascota.setText(null);
                txt_raza.setText(null);
                txt_edad.setText(null);
                txt_nombredueno.setText(null);
                txt_telefono.setText(null);
                
            }
        }
        catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Por favor ingrese un numero entero en la edad y el telefono");
                }
        
    }//GEN-LAST:event_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_mascota;
    private javax.swing.JTextField txt_nombredueno;
    private javax.swing.JTextField txt_raza;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    private void datos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}

