/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;




import Controlador.LogicaEmpleados;
import Modelo.Conexion;
import Modelo.empleados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.cert.PKIXRevocationChecker;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author duily
 */
public class crud_empleados extends javax.swing.JPanel {
    Conexion  coneccion = new Conexion();
    Connection cin = coneccion.getConnection();
    PreparedStatement ps;
    LogicaEmpleados logica = new LogicaEmpleados();
    private empleados empleados;
    
    
    

    /**
     * Creates new form crud_empleados
     */
    public crud_empleados() {
        initComponents();
        txt_usuario1.setEditable(false);
        Mostrar();
        


    }
    

    public void Mostrar (){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Cargo");
        modelo.addColumn("Codigo");
        modelo.addColumn("Autorizado");
        try{
            CallableStatement cmd = cin.prepareCall("{CALL lista_empleados}");
            ResultSet rs = cmd.executeQuery();
            while(rs.next())
            {
                Object dato [] = new Object[4];
                for (int i = 0; i < 4; i++) {
                    dato[i]=rs.getString(i+1);   
                }
                modelo.addRow(dato);
                
            }
            jTable_empleados.setModel(modelo);
        } catch(Exception e){
            
        }
    }

    public void autorizar(){
        String autorized = "exec autorizar @codigo = ?";
        
        try{
            ps = cin.prepareCall(autorized);
            ps.setString(1, txt_usuario1.getText());
            int generar = ps.executeUpdate();
            Mostrar();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    public void eliminar(){
        String delete = "exec eliminar @codigo = ?";
         try{
            ps = cin.prepareCall(delete);
            ps.setString(1, txt_usuario1.getText());
            int generar = ps.executeUpdate();
            Mostrar();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }      
    }
    
    public void modificar(){
        String modificar_sn = "exec modificar_sn  ?,?,?";
        String modificar_con = "execmodificar_cn ?,?,?,?";
        try{
            ps = cin.prepareCall(modificar_sn);
            ps.setString(1, text_nombre.getText());
            ps.setString(2, text_cargo.getText());
            ps.setString(3, txt_usuario1.getText());
            int generar = ps.executeUpdate();
            Mostrar();
            System.out.println("sn");
        }
        catch(Exception b){
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_empleados = new javax.swing.JTable();
        txt_usuario1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_cargo = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        autorizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        eliminar1 = new javax.swing.JButton();
        txt_contra = new javax.swing.JTextField();

        setBackground(new java.awt.Color(247, 247, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 82, 94));
        jLabel1.setText("Contraseña:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 160, 30));

        jTable_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_empleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_empleados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 310));

        txt_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuario1ActionPerformed(evt);
            }
        });
        add(txt_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 150, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 82, 94));
        jLabel2.setText("Gestión de empleados");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 82, 94));
        jLabel3.setText("Nombre Empleado:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 160, 30));

        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 150, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 82, 94));
        jLabel4.setText("Cargo:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 160, 30));

        text_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cargoActionPerformed(evt);
            }
        });
        add(text_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 150, 30));

        btn_modificar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(71, 82, 94));
        btn_modificar.setText("Modificar");
        btn_modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 80, -1));

        autorizar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        autorizar.setForeground(new java.awt.Color(71, 82, 94));
        autorizar.setText("Autorizar");
        autorizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        autorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizarActionPerformed(evt);
            }
        });
        add(autorizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 80, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 82, 94));
        jLabel5.setText("Codigo Empleado:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 160, 30));

        eliminar1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        eliminar1.setForeground(new java.awt.Color(71, 82, 94));
        eliminar1.setText("Eliminar");
        eliminar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });
        add(eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 80, -1));

        txt_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraActionPerformed(evt);
            }
        });
        txt_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contraKeyReleased(evt);
            }
        });
        add(txt_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuario1ActionPerformed

    }//GEN-LAST:event_txt_usuario1ActionPerformed

    private void jTable_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_empleadosMouseClicked
        int fila = jTable_empleados.rowAtPoint(evt.getPoint());
        text_nombre.setText(String.valueOf(jTable_empleados.getValueAt(fila, 0)));
        text_cargo.setText(String.valueOf(jTable_empleados.getValueAt(fila, 1)));
        txt_usuario1.setText(String.valueOf(jTable_empleados.getValueAt(fila, 2)));
        
        
        
        
    }//GEN-LAST:event_jTable_empleadosMouseClicked

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void text_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cargoActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        modificar(); 

      
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void autorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizarActionPerformed
        autorizar();

    }//GEN-LAST:event_autorizarActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        eliminar();// TODO add your handling code here:
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void txt_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraActionPerformed

    private void txt_contraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contraKeyReleased

    }//GEN-LAST:event_txt_contraKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton autorizar;
    public javax.swing.JButton btn_modificar;
    public javax.swing.JButton eliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_empleados;
    public javax.swing.JTextField text_cargo;
    public javax.swing.JTextField text_nombre;
    public javax.swing.JTextField txt_contra;
    public javax.swing.JTextField txt_usuario1;
    // End of variables declaration//GEN-END:variables


}