/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;


import Controlador.LogicaEmpleados;
import Modelo.empleados;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author duily
 */
public class registro extends javax.swing.JPanel {
    
    private Login login;
    private empleados empleados;
    LogicaEmpleados logica = new LogicaEmpleados();

    /**
     * Creates new form registro
     */
    public registro(Login login) {
        this.login =login;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpregistro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        r_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        r_contrasena = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        r_cargo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        r_codigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        label_iniciasesion = new javax.swing.JLabel();

        jpregistro.setBackground(new java.awt.Color(255, 255, 255));
        jpregistro.setForeground(new java.awt.Color(255, 255, 255));
        jpregistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(71, 82, 94));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 82, 94));
        jLabel3.setText("Contraseña:");
        jLabel3.setPreferredSize(new java.awt.Dimension(10, 31));
        jpregistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 250, 20));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>Registrate con tu numero de empleado<html>");
        jLabel4.setPreferredSize(new java.awt.Dimension(10, 31));
        jpregistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 450, 110));

        r_nombre.setForeground(new java.awt.Color(129, 144, 165));
        r_nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        r_nombre.setCaretColor(new java.awt.Color(129, 144, 165));
        r_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_nombreActionPerformed(evt);
            }
        });
        jpregistro.add(r_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 380, 30));

        jLabel6.setBackground(new java.awt.Color(71, 82, 94));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(71, 82, 94));
        jLabel6.setText("Nombre empleado:");
        jLabel6.setPreferredSize(new java.awt.Dimension(10, 31));
        jpregistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 250, 20));

        r_contrasena.setForeground(new java.awt.Color(150, 159, 170));
        r_contrasena.setAutoscrolls(false);
        r_contrasena.setSelectedTextColor(new java.awt.Color(150, 159, 170));
        r_contrasena.setSelectionColor(new java.awt.Color(150, 159, 170));
        r_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_contrasenaActionPerformed(evt);
            }
        });
        jpregistro.add(r_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 380, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondo_login2.png"))); // NOI18N
        jpregistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 260, 220));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("¿Ya tienes cuenta ?");
        jpregistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 150, 20));

        jLabel11.setBackground(new java.awt.Color(71, 82, 94));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(71, 82, 94));
        jLabel11.setText("Cargo de empleado:");
        jLabel11.setPreferredSize(new java.awt.Dimension(10, 31));
        jpregistro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 250, 20));

        r_cargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mesero", "Cajero", "Cocinero", "Encargado" }));
        jpregistro.add(r_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 380, -1));

        jLabel12.setBackground(new java.awt.Color(71, 82, 94));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(71, 82, 94));
        jLabel12.setText("Codigo de empleado:");
        jLabel12.setPreferredSize(new java.awt.Dimension(10, 31));
        jpregistro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 250, 20));

        r_codigo.setForeground(new java.awt.Color(129, 144, 165));
        r_codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        r_codigo.setCaretColor(new java.awt.Color(129, 144, 165));
        r_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_codigoActionPerformed(evt);
            }
        });
        jpregistro.add(r_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 380, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_registro.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpregistro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 170, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondo_login.png"))); // NOI18N
        jpregistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 540));

        label_iniciasesion.setBackground(new java.awt.Color(119, 211, 83));
        label_iniciasesion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label_iniciasesion.setForeground(new java.awt.Color(119, 211, 83));
        label_iniciasesion.setText("INICIA SESIÓN");
        label_iniciasesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_iniciasesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_iniciasesionMouseClicked(evt);
            }
        });
        jpregistro.add(label_iniciasesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpregistro, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpregistro, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void r_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_nombreActionPerformed

    private void r_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_contrasenaActionPerformed

    private void r_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_codigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nombre = r_nombre.getText();
        String codigo = r_codigo.getText();
        String cargo = (String) r_cargo.getSelectedItem();
        String contrasena = r_contrasena.getText();
        registrar(nombre,cargo,codigo,contrasena);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void label_iniciasesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_iniciasesionMouseClicked
        ingresar();
    }//GEN-LAST:event_label_iniciasesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpregistro;
    private javax.swing.JLabel label_iniciasesion;
    private javax.swing.JComboBox r_cargo;
    private javax.swing.JTextField r_codigo;
    private javax.swing.JPasswordField r_contrasena;
    public javax.swing.JTextField r_nombre;
    // End of variables declaration//GEN-END:variables


    private void ingresar(){
        login.iringreso(this);
    }
    
    private void registrar(String nombre, String cargo, String codigo,String contrasena){
            if (nombre.equals("") || cargo.equals("") || codigo.equals("") || contrasena.equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios");
            }
            else{
                String dato = logica.validar(codigo);
                if(dato != ""){
                    logica.registro(nombre, cargo, codigo, contrasena);
                    JOptionPane.showMessageDialog(null, "Registro exitoso");
                    ingresar();                     
                }else{
                    JOptionPane.showMessageDialog(null, "El codigo de empleado ya se encuentra registrado","Validar los codigo existentes",JOptionPane.WARNING_MESSAGE);
                    r_codigo.setText(null);
                    r_contrasena.setText(null);                       
                } 
            }           
        }
}
