/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author duily
 */

import Controlador.LogicaEmpleados;
import Modelo.empleados;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import static sun.security.jgss.GSSUtil.login;

public class ingreso extends javax.swing.JPanel {
    private Login login;
    private empleados empleados;// traemos el objeto empleados
    LogicaEmpleados logica = new LogicaEmpleados();// aqui traemos la clase logica de empleados

    /**
     * Creates new form ingreso
     */
    public ingreso(Login login) {
        this.login=login;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpingreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        icodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        icontrasena = new javax.swing.JPasswordField();
        b_ingresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_registrate = new javax.swing.JLabel();

        jpingreso.setBackground(new java.awt.Color(255, 255, 255));
        jpingreso.setForeground(new java.awt.Color(255, 255, 255));
        jpingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(71, 82, 94));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 82, 94));
        jLabel3.setText("Contraseña:");
        jLabel3.setPreferredSize(new java.awt.Dimension(10, 31));
        jpingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 250, 20));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Inicia sesión o registrate");
        jLabel4.setPreferredSize(new java.awt.Dimension(10, 31));
        jpingreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 440, 70));
        jpingreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 400, 10));

        icodigo.setForeground(new java.awt.Color(129, 144, 165));
        icodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        icodigo.setCaretColor(new java.awt.Color(129, 144, 165));
        icodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icodigoActionPerformed(evt);
            }
        });
        jpingreso.add(icodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 380, 30));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Ingresa tu codigo y contraseña de empleados:");
        jLabel5.setPreferredSize(new java.awt.Dimension(10, 31));
        jpingreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 300, -1));

        jLabel6.setBackground(new java.awt.Color(71, 82, 94));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(71, 82, 94));
        jLabel6.setText("Código de empleado:");
        jLabel6.setPreferredSize(new java.awt.Dimension(10, 31));
        jpingreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 250, 20));

        icontrasena.setForeground(new java.awt.Color(150, 159, 170));
        icontrasena.setAutoscrolls(false);
        icontrasena.setSelectedTextColor(new java.awt.Color(150, 159, 170));
        icontrasena.setSelectionColor(new java.awt.Color(150, 159, 170));
        icontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icontrasenaActionPerformed(evt);
            }
        });
        jpingreso.add(icontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 380, 30));

        b_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/boton_ingresar.jpg"))); // NOI18N
        b_ingresar.setBorder(null);
        b_ingresar.setBorderPainted(false);
        b_ingresar.setContentAreaFilled(false);
        b_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ingresarActionPerformed(evt);
            }
        });
        jpingreso.add(b_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 160, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondo_login2.png"))); // NOI18N
        jpingreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 260, 220));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<html>¡Unete al EL EJECUTIVO, y empiza a gestionar las ordenes de tus comensales!<html>");
        jLabel9.setPreferredSize(new java.awt.Dimension(10, 31));
        jpingreso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 280, 70));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("¿Aun no tienes cuenta?");
        jpingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 170, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondo_login.png"))); // NOI18N
        jpingreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));

        label_registrate.setBackground(new java.awt.Color(119, 211, 83));
        label_registrate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label_registrate.setForeground(new java.awt.Color(119, 211, 83));
        label_registrate.setText("REGISTRATE");
        label_registrate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_registrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_registrateMouseClicked(evt);
            }
        });
        jpingreso.add(label_registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void icodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icodigoActionPerformed

    private void icontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icontrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icontrasenaActionPerformed

    private void b_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ingresarActionPerformed
           String codigo = icodigo.getText();
           String contrasena = icontrasena.getText();
           iniciarsesion(codigo, contrasena);
    }//GEN-LAST:event_b_ingresarActionPerformed

    private void label_registrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registrateMouseClicked
        registrarse();
    }//GEN-LAST:event_label_registrateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_ingresar;
    private javax.swing.JTextField icodigo;
    private javax.swing.JPasswordField icontrasena;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpingreso;
    private javax.swing.JLabel label_registrate;
    // End of variables declaration//GEN-END:variables

    private void registrarse() {
        login.irregistro(this);
    }
    private void irhome(){
        login.irahome(this);
    }
    
    private void iniciarsesion(String codigo, String contrasena){
        if (codigo.equals("") || contrasena.equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios");
        }
        else{
            empleados datos = logica.iniciarSesion(codigo, contrasena);
            if(datos != null){
                if(datos.getAutorizado().equals("SI")){
                    JOptionPane.showMessageDialog(null, "Bienvenido: "+datos.getNombre());
                    irhome();
                }
                else{
                    JOptionPane.showMessageDialog(null, "El codigo de empleado no se encuentra autorizado","Pida Autorización de su Jefe",JOptionPane.WARNING_MESSAGE);
                    
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "codigo de empleado o contrasena no se encuentra registrado");
            }
        }
        
    }


}
